## EPIPUTANT
## GOAL: SCRIPT TO MONITOR THE EFFECT OF THE MUTATIONS OF NEW SARS-COV2 VARIANTS IN THE PREDICTED EPITOPES.
## INPUTS:
  ## PREDICTED EPITOPES & PARENTAL PROTEIN & LOCATION
  ## VARIANT: MUTATIONS, PARENTAL PROTEIN & LOCATION
  
## OUTPUTS:
  ## AFFECTED EPITOPE: YES / NO
  ## NEW PREDICTION OF AFFECTED EPITOEPS USING DISCOTOPE, BEBIPRED AND ABC PRED.
  
## FIRST TASK: MONITOR SARS2 VARIANTS, GET POSITIONS AFFECTED AND RECALCULATE EPITOPES AFFECTED WITHIN RBD.
